---

# - import_playbook: pb.vpls_datamodel.yml
#   when: vpls_data is not defined

- name: Deploy VPLS on Juniper
  hosts: pe
  gather_facts: no
  tasks:
    - name: Generate VPLS Configuration
      import_role:
        name: deploy_vpls
      vars:
        ansible_connection: local

      
