---
- name: Build Folder Structure
  hosts: core
  gather_facts: no
  vars:
    ansible_connection: local
  vars_files:
    - vpls_design.yml
  tasks:
    - name: Generate L3VPN Datamodel
      import_role:
        name: vpls_datamodel
      when: "'pe' in group_names"

        
