# BEGIN ANSIBLE MANAGED BLOCK
---
vpls_circuits:
    BNG_01:
        id: 1001
        links:
            - interface: ge-0/0/2
              vlan: 4001
              site_id: 2
    BNG_02:
        id: 1002
        links:
            - interface: ge-0/0/2
              vlan: 4002
              site_id: 2
# END ANSIBLE MANAGED BLOCK
